http_port: 14090
jwt_secret: "jwt_secret"
gpt:
  endpoint: "https://api.openai.com/v1"
  api_key: ""
  proxy_url: ""
search:
  github:
    tokens:
      - ""
  serper:
    endpoint: "https://google.serper.dev/search"
    api_key: ""
  bing:
    endpoint: "https://api.bing.microsoft.com/v7.0/search"
    api_key: ""
  searxng:
    endpoint: ""
redis:
  url:
  port: 6379
  password:
mysql:
  host: ""
  port: 3306
  user: ""
  password: ""
  db_name: ""
  slow_threshold: 200
  auto_migrate: false
supabase:
  url: ""
  key: ""
  jwt_secret: ""

# Chat Models and Weights
chat_models:
  - model: "deepseek/deepseek-chat"
    display: "deepseek-chat"
    weight: 2
  - model: "openai/gpt-3.5-turbo"
    display: "gpt-3.5-turbo"
  - model: "cohere/command-r"
    display: "command-r"
  - model: "anthropic/claude-3-haiku"
    display: "claude-3-haiku"
  - model: "google/gemini-flash-1.5"
    display: "gemini-flash-1.5"

# Rewrite Models and Weights
rewrite_models:
  - model: "deepseek/deepseek-chat"
    display: "deepseek-chat"
  - model: "openai/gpt-3.5-turbo"
    display: "gpt-3.5-turbo"
  - model: "cohere/command-r"
    display: "command-r"
  - model: "anthropic/claude-3-haiku"
    display: "claude-3-haiku"
  - model: "google/gemini-flash-1.5"
    display: "gemini-flash-1.5"
